apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-springboot-mysql-deployment
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef:
                  name: db-configmap
                  key: DB_HOST

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef:
                  name: db-configmap
                  key: DB_NAME

            - name: DB_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: order-springboot-mysql-service
spec:
  selector:
    app: order
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
