spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/student_directory
    username: springstudent
    password: springstudent
    #url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #username: ${DB_USER}
    #password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update   # Options: none, validate, update, create, create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false